//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspTestTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostingPlan
    {
        public HostingPlan()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public int Id { get; set; }
        public string Hosting { get; set; }
        public bool Paying { get; set; }
        public decimal Plan { get; set; }
    
        public virtual ICollection<Site> Sites { get; set; }
    }
}
